### PR TITLE
Added INFO function in c# wrapper

### PR DESCRIPTION
**Pull request by estradanic**
Very useful for unit conversions.

### CODE REVIEW

**Comment by ianhbell** [comment]
Thanks! Have you tested this functionality?  It looks fine, but I just want confirmation before I merge it.

**Comment by estradanic** [comment]
Yes. I actually needed it in a project I'm working on, and the pull request was somewhat of an afterthought lol.

**Comment by ianhbell** [comment]
Thanks, merged

**Comment by estradanic** [comment]
👍

**Pull request merged**
