### PR TITLE
Osx excel

### PR DESCRIPTION
**Pull request by hopalonghopper**
Updated README with instructions for getting REFPROP to work in OSX Excel (version 16.29 as part of Office 365). Also updated the REFPRP91.XLA VB script to include a check for OSX and instructions for editing the file for use in OSX.

### CODE REVIEW

**Comment by ianhbell** [comment]
Whoah, this is AWESOME! I've tried to do this many times, glad to hear we finally have a solution!

**Comment by ianhbell** [comment]
Can you please not include the changes to REFPRP91.xla? I'd prefer to keep that file unmodified since it it the version that came with REFPROP 9.1.

**Comment by hopalonghopper** [comment]
sure thing. I will put the changes required in the readme. Also, if I am submitting this info incorrectly please let me know, I'm new to all this :)

**Comment by ianhbell** [comment]
You're doing fine!  There is a learning curve for everyone, myself included, and I still have yet much to learn.

**Comment by ianhbell** [comment]
I think you wanted to remove REFPRP91.xla from your branch, not from the repo :)

**Comment by hopalonghopper** [comment]
I hate to play my n00b card here, but I cannot figure out how to fix the wrong i created on this REFPRP91.XLA file...any advise would be greatly appreciated :)

**Comment by hopalonghopper** [comment]
Let's just go the easy route and save time; this was a fantastic learning experience on what not to do...sorry for that :/

**Comment by ianhbell** [comment]
Don’t worry - I regularly destroy things when trying to be “smart” in git. And I’ve been using git every day for almost 10 years.

**Pull request closed without merging**
