### PR TITLE
Add High-Level API functions from REFPROP 10 to Mathcad Wrapper

### LINKED ISSUE #494: Mathcad add-in does not find REFPROP on start
FINAL EDIT 24Dec22: Looks like I took "NIST REFPROP 9.1 or later" too literally. I actually did a bit of diving into the code and discovered that it is only meant to work with V9 and NOT v10.  In light of this, I suppose my question has now become "will there be support for v10 of RefProp at any point in time?"

I have successfully compiled the PrimeREFPROPWrapper.dll using VS 2022 community edition. It places the dll in the correct Mathcad directory upon completion.  However, whenever I start Mathcad, I receive the "NIST RefProp Add-In" message dialog that says: "Add-in requires later version of REFPROP. Make sure that NIST RefProp 9.1.1 or later is installed." I clearly have the program installed in the default location (The executable is here: "C:\Program Files (x86)\REFPROP\REFPROP.EXE"). I tried a debug on the dll and I receive this message when I first step in:

image

I am at a loss as to where to go from here. I am pretty convinced that I had everything properly set to create an X64 output for this dll, but I am definitely not a professional programmer so there surely are things I am overlooking. Any help would be greatly appreciated. Thanks!

EDIT 24DEC22: I uncommented lines 329-333 of refprop.cpp which I will call the "debugging pop-up" which reports "The NIST RefProp DLL was found. Version: RPVersion_loaded". When I run Mathcad now, I get this pop-up:

image

Since it appears to be finding the appropriate 64-bit version, this just further adds to my confusion. I also want to add that I have the user environment variable of NIST_PATH = C:\Program Files (x86)\REFPROP. Just hoping to add more info in case someone can help. Thanks again!

### PR DESCRIPTION
**Pull request by henningjp**
### Description of the Change

This **Mathcad Wrapper Update (v2.1)** adds wrappers for the High-Level API Functions introduced in REFPROP 10, including:
- Code Updates for High-Level Functions
    - `rp_REFPROP( )`
    -  `rp_ERRMSG( )`
    - `rp_FLAGS( )`
    - `rp_GETENUM( )`
    - `rp_SETFLUIDS( )`
    - `rp_SETMIXTURE( )`
    - `rp_SETPATH( )`  (_allows for file browser through Mathcad interface_)
    - `rp_ALLPROPS0( )`   (**_beta feature_** - for single-phase, legacy API speeds, returning multiple properties at once)
- Updated Documentation (Mathcad Prime Docs only)
- Updated README with compilation and installation instructions
- Updated `Refprop_Units.mcdx` include file to add single `REFPROP( )` function that handles units
- Fixes version trigger for determining > version 9.1.1 and > version 10.0 ( Issue #494 )

### Benefits

- Provides much simpler interface to REFPROP through the `rp_REFPROP()` Function.
- Parameter simplification (using sensible defaults) to 4 or 5 parameters for `rp_REFPROP()`
- Unit handling is applied through the `Refprop_units.mcdx` include file via a user function `REFPROP( )` (no rp_ prefix)
- All functionality of the underlying `REFPROPdll` call is implemented, including setting of flags, information strings, etc.

### Possible Drawbacks

- Unit system is set to mass-based units for consistency with the Legacy API functions, these should not be changed.  Unit conversion can be handled directly in the Mathcad interface very easily.
- REFPROP() had to be split in to three separate functions because of Mathcad add-in restrictions:
    - `rp_REFPROP( )` - Returns array of numeric output properties
    - `rp_REFPROP1( )` - Returns single scalar value for a single property, no fluid specified
    - `rp_REFPROPc( )` - Returns a string for any information requests that return strings and no numeric values
- Call simplification removes several flag parameters in the REFPROP() functions from user control (sensible default applied)
- `ALLPROPSx( )` and `ABFLSH( )` are **_not_** implemented as they are limited to specific phase regions and functionality can be achieved through calls to `REFPROP( )`.
- In order to get `rp_ERRMSG( )` to work properly, retrieving the last known error, the variable `ierr` had to be made global.  This required a minor change to every single legacy API include file (one per function), resulting in a very large PR.  The single change at the top of each file is identical, however, and can be pretty much ignored for these updated header files.

### Verification Process

A Mathcad Prime 8.0 verification worksheet was created to rigorously test all new High-Level functions.  A PDF of this file is linked here ( [REFPROP10 Function Tests.pdf](https://github.com/usnistgov/REFPROP-wrappers/files/10530021/REFPROP10.Function.Tests.pdf) ) for viewing without a Mathcad Installation.  The actual Mathcad Prime file can be provided on request.

- *How did you verify that all new functionality works as expected?*  Verification sheet test all new functions, including error conditions.
- *How did you verify that all changed functionality works as expected?*  Values were compared to Legacy API calls to ensure that results and units were consistent.
- *How did you verify that the change has not introduced any regressions?* Verification sheets and documentation pages for full-range Legacy API functions and Mixture behavior were re-evaluated for regression testing.

### Applicable Issues

In addition to new functionality added, also Closes #494

### CODE REVIEW

**Comment by ianhbell** [comment]
Are we good to merge this? There's a lot to go through. I'm confused about this point in the docs: 

Parameter simplification (using sensible defaults) to 4 or 5 parameters for rp_REFPROP()

because around there you mention how you have in another function made REFPROP with 4 arguments and sensible defaults.

**Comment by henningjp** [comment]
Yes, confusion warranted.  The README may help.

There are 3-versions of the direct **Custom Function** DLL calls:
1. `rp_REFPROP(hFld, hIn, hOut, a, b)` - returns an array for multiple hOut values (5 params)
2. `rp_REFPROP1(hIn, hOut, a, b)` - returns a single scalar value, takes no fluid string (4 params)
3. `rp_REFPROPc(hFld, hIn, hOut, a, b)` - returns a character string (like for DLL# or CAS#) (5 params)

This is because of the fixed nature of the Mathcad code structures for Custom Functions (_from a C++  DLL_).

There's another **User Function** (_in Mathcad worksheet_) that is just `REFPROP(hFld, hIn, hOut, a, b)` (no `rp_` prefix and 5 params - did I say 4?) that is more flexible on parameters and return types and will call one of the three DLL functions depending on the parameters passed and returns any of the return types.  It also handles Mathcad units on inputs _a_ and _b_, as well as applying appropriate units to either the single scalar or array elements returned (obviously not if a character string is returned).  This is the simplest way to call REFPROPdll, but is slower than the direct calls above because of the units handling and parameter inspection.

Mathcad users will (should?) understand the difference.

**Comment by henningjp** [comment]
Take a look through the PDF I attached in the PR ( [REFPROP10 Function Tests.pdf](https://github.com/usnistgov/REFPROP-wrappers/files/10530021/REFPROP10.Function.Tests.pdf) ) for demonstration of the above.  It demonstrates (and verifies) every function added as well as comparing to the legacy API functions that were included originally and demonstrating that they still work.  The C++ wrappers and the Mathcad unit wrapper have been rigorously tested.  Of course, there's a lot of code there, which increases the likelihood of some condition that wasn't anticipated (spelled b-u-g), but I've been using it regularly and haven't run into any issues.  Note that the `PrimeManual.pdf` documentation file is generated from a LIVE set of Mathcad worksheets that provide additional verification of all of the functions.

The coding and testing started last November, '22 and is successfully completed as verified in the Mathcad sheet that the attached PDF was printed from.  It's ready to pull.

**Comment by ianhbell** [comment]
That documentation file is tremendous. Makes me a little jealous of what you can do in MathCAD, if I'm being honest. Especially how units are handled.

**Comment by henningjp** [comment]
@ianhbell - I understand.  I started using version 1.0 in 1987 (ran under DOS) and never looked back throughout my career.  There is literally nothing like it for documenting technical engineering work.  At my current engineering firm of 20 years, I am the "Mathcad Evangelist".  Thanks for the merge.

**Comment by henningjp** [comment]
@ianhbell - I was waiting for this PR to address the issue of finding a place to put the compiled add-in DLL for Mathcad so that people don't have to compile it.  We only need to provide a Windows version (which I can send you), but I didn't think it should go in the Repo as a binary would have to be updated for every patch/update.  It's only about 200Kb.  Thoughts?

**Comment by ianhbell** [comment]
I'm never sure what to do with binaries. One option is to put them as releases on github, here: https://github.com/usnistgov/REFPROP-wrappers/releases

But that is really intended for a situation where you have all binaries being generated in sync, like in CoolProp. Not sure what to do in this case.

**Comment by mdsrjw** [comment]
Thank you, Jeff, for all of your hard work. It is extremely valuable in the context of Mathcad. It is unfortunate that I used to have a working method that involved Excel when Mathcad was not owned by PTC (v15). It was broken when they switched over to their "Prime" product (they went the .NET route) and I've never found a means of replicating that methodology. This dll fixes that. Like you, Jeff, I have been using Mathcad from the get-go and prior to that had used TKSolver. Mathcad is a highly sophisticated tool Ian Bell - you should look into acquiring it someday.

**Comment by ianhbell** [comment]
For me I need deterministic code, and while I can very much see the appeal of the bells and whistles, unless I can get easy calling into C/C++ and cross-platform use without the need for a license, I doubt I'll make the transition.

**Comment by henningjp** [comment]
@ianhbell - You mentioned something before about an S3 bucket?

**Comment by ianhbell** [comment]
Indeed, that is an option.

**Comment by henningjp** [comment]
I have no clue what that is, only that you mentioned it.  Can we put the DLL there and just link to it from the README.md so that it will download?  Or is something more sophisticated and secure required?  I'll send you the DLL (zipped).

**Comment by ianhbell** [comment]
I think that could work. Only potential worry is that URL you get seems sketchy although it comes from NIST's S3 bucket.

**Pull request merged**
