### PR TITLE
Refactor Mathematica wrapper structure for Pactlet generation in MM13+

### PR DESCRIPTION
**Pull request by henningjp**
This is a complete restructuring of this wrapper to support the modern **_Paclet_** generation in Mathematica 13 and higher (current release is 14.0).  This is a long awaited change from Wolfram on the Mathematica product.  Actual code functionality has not changed at all, but unfortunately the entire wrapper directory will look like it's been tossed and completely replaced.  Since it is Wolfram Language code and the new help page templates contain many formatting changes, looking at these diffs will not be helpful.

**Benefits:**
- Wolfram has formally implemented the **_Paclet_** feature for development, generation, and installation of add-in packages.
- No 3rd party editors or build tools (Eclipse and Wolfram Workbench) are required by the end user who wants to use this wrapper.
- The build tools for the wrapper paclet, including **_Documentation Tools_** are now part of the Mathematica interface.
- The "build" documentation files no longer have to be stored in the repository as they can be generated on the fly by the end user, using only Mathematica 13.2 or later (some minor bugs in 13.0 and 13.1).
- Help Documentation pages for RefProp are now beautifully formatted to match Mathematica's built-in help pages.
- The entire repository is now text readable, for commit tracking on GitHub.
- ToolTips and Help links in the hover buttons work on all RefpropLink function names in the Mathematica notebooks.

**Changes:**
- Removed and ignore the build directory (it is generated by the user/developer)
- Reformat all Help documentation in the new Doc Tools temples for Mathematica Help system.
- Restructure the directory to match the official **_Paclet_** directory structure supported by Mathematica 13+

**Testing and Verification**
- All help pages have been regenerated (with no errors), installed in Mathematica 13, and inspected for cross-links, external links, and functionality.
- Help page regeneration provides regression testing of the RefProp functions in the package.

### CODE REVIEW

**Comment by ianhbell** [comment]
Is this all ready to merge?

**Comment by henningjp** [comment]
Yes.

I've been sitting on this PR until MM v14 was released (which is also tested) so this restructure didn't require the latest cutting edge release.  We're a major and minor release past the required v13.2.  I've been using these changes for almost a year now, with no side effects.

**Comment by ianhbell** [comment]
One last question: does it make sense to keep the old files around somewhere? Move them into a subfolder or something?

**Comment by henningjp** [comment]
Can't someone just checkout the previous commit in the history?  Not sure who would want to, unless they only have MM 12. Even it won't run on anything earlier than 12.

Also, I'm working on putting the installation paclet on the Wolfram Paclet Server for even easier access to the new version.

**Comment by ianhbell** [comment]
Suppose so. I'll go ahead and merge.

**Comment by henningjp** [comment]
If you want to, let's put some tags on to make it easier to find.   

Tag the commit in this last PR commit (1237f7f4c571fe86f5572f31314e633acdc1889c) as **_Mathematica v1.1_**,   Then tag my last previous commit (7e0384c787a825db2ab42ae1b19cf60e930330d7) as **_Mathematica 1.0_**.

**Comment by ianhbell** [comment]
Ok, I did the tagging you suggest : https://github.com/usnistgov/REFPROP-wrappers/tags (spaces not permitted in tag names)

**Comment by Happiness-in-Danger** [comment]
@henningjp In MMA14,there are some problems.
image

**Comment by henningjp** [comment]
@Happiness-in-Danger - You should open an actual Issue for this, rather than adding a comment to this pull request.

I'm running on MMA14 (14.0.0.0 to be exact) with no issues.

Your screenshot error message indicates that NIST REFPROP is not found or you have an older version, or possibly it's not inthe default location on your machine.

The Needs command should come back with:
image

If you don't see that green banner, the wrapper couldn't find REFPROP.

Also, REFPROP v9.1 or v10.0 must be installed.  The error message you are getting indicates that it can't determine the version of NIST REFPROP that you are using.  Versions earlier than v9.1 are not supported.

Please open an **Issue** with your original post and indicate which version of NIST REFPROP you have.

**Pull request merged**
